### ISSUE TITLE
Catch version-incompatibility between Vagrant and VirtualBox

### ISSUE THREAD

**Issue by baccenfutter** [metacloud/molecule#1295]
# Issue Type

- Bug report

# Desired Behavior

Not all versions of Vagrant work together with all versions of VirtualBox. For instance, `Vagrant-1.8.x` does not work with `VirtualBox-5.1.x`. Molecule doesn't check for compatibility and happily fires Vagrant against an unsupported VirtualBox leading to obscure and slighlt misleading Python exceptions, such as:

```
AttributeError: 'NoneType' object has no attribute 'splitlines'
```

*(you can probably imaging, that it can take several hours even for an educated operator to get from that exception in Molecule to a version mismatch between Vagrant and VirtualBox)*

# Actual Behaviour
Provide the user with a human-readable, understandable and solution-oriented error message, if Molecule detects that the installed Vagrant version is not compatible with the installed VirtualBox version.

**Comment by retr0h** [comment]
I believe this is fixed in #1285, which hasn't been released yet.

**Comment by baccenfutter** [comment]
Sweet! I ran into it the other day, today my colleague ran into it and wasted a few hours on it.
